### ISSUE TITLE
Add more operators

### ISSUE THREAD

**Issue by spierceVR** [MinecraftU/2022-computer-adventures-pringlelang#15]
We still need to implement the functionality for the following tokens / operators

- [x] ``&`` (boolean and)
- [x] ``|`` (boolean or)
- [x] ``!`` (boolean negate)
- [x] ``=`` (boolean comparison)
- [x] ``<`` (less than)
- [x] ``>`` (greater than)
- [x] ``%`` (modulo)
- [x] ``^`` (exponent)
- [x] ``*`` (binary multiply)
- [x] ``/`` (binary divide)
- [x] ``+`` (binary add)
- [x] ``-`` (binary subtract)

**Comment by jamespeilunli** [comment]
Merged PR #21 did not close this issue; I'm manually doing it.
