### ISSUE TITLE
Add variables

### ISSUE THREAD

**Issue by jamespeilunli** [MinecraftU/2022-computer-adventures-pringlelang#8]
- [x] Define new variables
- [x] assign values to variables

**Comment by spierceVR** [comment]
One way other stack oriented languages implement variables is by having a separate stack of dictionaries (aka maps) that store key-value pairs representing the variable identifier and the variable's value.

https://en.wikipedia.org/wiki/Stack-oriented_programming#:~:text=Some%20stack-oriented%20languages%20operate,multiply%203%20(infix%20notation)

### PostScript stacks
PostScript and some other stack languages have other separate stacks for other purposes.

#### Variables and dictionaries
The evaluation of different expressions has already been analyzed. The implementation of variables is important for any programming language, but for stack-oriented languages it is of special concern, as there is only one way to interact with data.

The way variables are implemented in stack-oriented languages such as PostScript usually involves a separate, specialized stack which holds dictionaries of [key–value pairs](https://en.wikipedia.org/wiki/Key%E2%80%93value_pair). To create a variable, a key (the variable name) must be created first, with which a value is then associated. In PostScript, a name data object is prefixed with a `/`, so `/x` is a name data object which can be associated with, for example, the number 42. The define command is `def`, so

`/x 42 def`

associates with the name `x` with the number 42 in the dictionary atop the stack. A difference exists between `/x `and `x` – the former is a data object representing a name, `x` stands for what is defined under `/x`.
